apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapps
spec:
  destination:
    name: ''
    namespace: myapps
    server: 'https://kubernetes.default.svc'
  source:
    path: myapps
    repoURL: 'https://github.com/pmmz007/azure-k8s.git'
    targetRevision: HEAD
  sources: []
  project: demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

